name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
        VERSION: ${{ github.event.inputs.version }}
        BRANCH: release-${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Set up Git
        run: |
          git config --add user.name "TrendATI-bot"
          git config --add user.email "ati-integration@trendmicro.com"
      - name: Run build
        run: |
          pip install --upgrade hatch
          hatch version ${{ env.VERSION }}              
          hatch --verbose build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
      - name: Merge release branch
        run: |
          git commit -am "Release ${{ env.VERSION }}: increment version"
          git checkout main
          git merge --no-ff ${{ env.BRANCH }}
          git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
          git checkout ${{ env.BRANCH }}
          git merge main
          git checkout develop
          git merge --no-ff ${{ env.BRANCH }}
          git push --atomic origin main develop ${{ env.BRANCH }} refs/tags/${{ env.VERSION }}